url: //petrosh.github.io/carello.js

baseurl: /carello.js

permalink: pretty
# or permalink: /:categories/:title/

# rouge -> is currently unsupported on GitHub Pages
highlighter: pygments

markdown: rouge
kramdown:
  auto_ids: true

gems: [jekyll-coffeescript]

sass:
  sass_dir: _sass
  style: compressed

github:
  repo: https://github.com/petrosh/carello.js
